apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: exhibition-fe-ingress
spec:
  $patch: replace
  tls:
    - hosts:
        - exhibition.scg.sh
        - swgp.exhibition.scg.sh
        - exhibition.scg.skku.ac.kr
        - scg.exhibition.scg.sh
        - exhibition2.scg.skku.ac.kr
        - swgp.exhb.scg.skku.ac.kr
        - aiswm.exhb.scg.skku.ac.kr
      secretName: gitops-tls
  rules:
    - host: exhibition.scg.sh
      http: &feHttp
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: exhibition-fe-service
                port:
                  number: 80
    - host: swgp.exhibition.scg.sh
      http: *feHttp
    - host: exhibition.scg.skku.ac.kr
      http: *feHttp
    - host: scg.exhibition.scg.sh
      http: *feHttp
    - host: exhibition2.scg.skku.ac.kr
      http: *feHttp
    - host: swgp.exhb.scg.skku.ac.kr
      http: *feHttp
    - host: aiswm.exhb.scg.skku.ac.kr
      http: *feHttp

