apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exhibition-fe
resources:
- namespace.yaml
- ../../base/fe

patches:
- path: domain.yaml
  target:
    kind: Ingress
    name: exhibition-fe-ingress
images:
- name: scgskku/exhibition-fe
  newTag: 1e8a92ecedf2644a372336085b5c8ff73136c841
