apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exhibition-fe
resources:
- namespace.yaml
- ../../base/fe

patches:
- path: domain.json
  target:
    kind: Ingress
    name: exhibition-fe-ingress
images:
- name: scgskku/exhibition-fe
  newTag: 1787971d5ede93c8c39da3ca796946c1d6ae8eb3
