apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exhibition-be
resources:
- namespace.yaml
- secret.yaml
- ../../base/be


patches:
- path: domain.yaml
  target:
    kind: Ingress
    name: exhibition-be-ingress
images:
- name: scgskku/exhibition-be
  newTag: 5bbfc65c9bc90e80e9098c1fad963b36f0f79088
