apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exhibition-be
resources:
- namespace.yaml
- secret.yaml
- ../../base/be


patches:
- path: domain.yaml
  target:
    kind: Ingress
    name: exhibition-be-ingress
images:
- name: scgskku/exhibition-be
  newTag: ae29d7e16b1bcfdec0a9470707ac2f2439682321
